joints_to_ign:
    - 1
    - 9
    - 12
flat_hand_mean: False
df_cone_height: 0.0001
ign_part_pairs: ["9,16", "9,17", "6,16", "6,17", "1,2", "12,22"]
penalize_outside: True
max_collisions: 128
load_scene: True


num_gaussians: 8
interpenetration: True
optim_type: 'lbfgsls'
lr: 1.0
maxiters: 30
interactive: True
visualize: False
rho: 100
ftol: 1e-9
gtol: 1e-9
gender: "male"
model_type: 'smplx'
use_pca: True
num_pca_comps: 12
flip: True
use_joints_conf: True
trans_opt_stages:
    - 2
    - 3
    - 4
    - 5
    - 6
use_vposer: True


camera_mode: 'fixed'
focal_length_x: 1060.53
focal_length_y: 1060.38
camera_center_x: 951.30
camera_center_y: 536.77


output_folder: '/media/dangbowen/Data/PROX/output'
result_folder: 'results'
prior_folder: 'priors'
model_folder: '/media/dangbowen/Data/PROX/models'
part_segm_fn: '/media/dangbowen/Data/PROX/smplx_parts_segm.pkl'
vposer_ckpt: '/media/dangbowen/Data/PROX/vposerDecoderWeights.npz'


contact: True
contact_angle: 45
rho_contact: 5e-2
contact_loss_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1e4


sdf_penetration: True
sdf_penetration_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1e2
    - 1.0
#    - 1e3
#    - 1e3
#    - 1e3
#    - 1e3
#    - 1e3
#    - 1e3
#    - 1e3


init_mode: 'scan'
m2s: True
rho_m2s: 5e-1
m2s_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
s2m: True
rho_s2m: 2e-1
s2m_weights:
    - 1.0
    - 1.0
    - 1e2
    - 5e2
    - 5e2
    - 5e2
    - 5e2
mask_on_color: True
read_depth: True
read_mask: True


shape_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
data_weights:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
body_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4e0
    - 4.78e0
    - 4.78e0
    - 4.78e0
    - 4.78e0
coll_loss_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.01
    - 0.01
    - 0.01
    - 0.01
expr_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
hand_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4
    - 4.78
    - 4.78
    - 4.78
    - 4.78
jaw_pose_prior_weights:
    - 4.04e03,4.04e04,4.04e04
    - 4.04e03,4.04e04,4.04e04
    - 574,5740,5740
    - 47.8,478,478
    - 47.8,478,478
    - 47.8,478,478
    - 47.8,478,478
hand_joints_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 2.0
    - 2.0
    - 2.0
face_joints_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 2.0
    - 2.0
    - 2.0


body_prior_type: 'l2'
left_hand_prior_type: 'l2'
right_hand_prior_type: 'l2'
jaw_prior_type: 'l2'


dataset: 'openpose'
use_cuda: True
float_dtype: "float32"


use_hands: True
use_face: True


drop_noise: False
eps: 0.15
min_samples: 100
new_depth_loss: False
use_ini_pose: False
use_joints_loss_3d: False
joints_3d_weight:
    - 0.0
    - 0.0
    - 0.0
    - 10.0
    - 10.0
    - 0.0
    - 0.0
joint_penetration: False
joint_penetration_weight:
    - 1.0e2
    - 1.0e2
    - 1.0e2
    - 1.0e2
    - 1.0e2
    - 1.0e2
    - 1.0e2